# curl --location --request GET 'http://localhost:8080/api/redis/strings/database:redis:creator'
GET http://localhost:8080/api/redis/strings/database:redis:creator

###

# curl --location --request POST 'http://localhost:8080/api/redis/strings'
# --header 'Content-Type: application/json'
# --data-raw '{ "database:redis:creator": "Salvatore Sanfilippo" }'
POST http://localhost:8080/api/redis/strings
Content-Type: application/json

{ "database:redis:creator": "Salvatore Sanfilippo" }

###

# curl --location --request GET 'http://localhost:8080/api/books/search/?q=%25scal%25'
GET http://localhost:8080/api/books/search/?q=%25scal%25

###

# curl --location --request GET 'http://localhost:8080/api/books/authors/?q=brian%20s'
GET http://localhost:8080/api/books/authors/?q=brian%20w

###
# curl --location --request GET 'http://localhost:8080/api/recommendations/user/55214615117483454'
GET http://localhost:8080/api/recommendations/user/55214615117483454

###
# curl --location --request GET 'http://localhost:8080/api/recommendations/isbn/1789610222/pairings'
GET http://localhost:8080/api/recommendations/isbn/1789610222/pairings

###
GET http://localhost:8080/api/books/search?q=java